// Curated photos of completed projects (logros), shown in the Logros section.
export const gallery = [
  { file: 'logro-01.jpg', year: 2023, es: 'Limpieza en Israel tras el 7 de octubre', en: 'Cleanup in Israel after October 7th' },
  { file: 'logro-02.jpg', year: 2024, es: 'Kits de Purim listos para entregar', en: 'Purim kits ready to deliver' },
  { file: 'logro-03.jpg', year: 2024, es: 'Entrega de regalos en el hospital', en: 'Delivering gifts at the hospital' },
  { file: 'logro-04.jpg', year: 2024, es: 'Visitando a un soldado herido', en: 'Visiting a wounded soldier' },
  { file: 'logro-05.jpg', year: 2024, es: 'Entrega de lulav y etrog a soldados', en: 'Delivering lulav and etrog to soldiers' },
  { file: 'logro-06.jpg', year: 2024, es: 'Soldados celebrando Sukot', en: 'Soldiers celebrating Sukkot' },
  { file: 'logro-08.jpg', year: 2024, es: 'Arba minim en el hospital', en: 'Four species at the hospital' },
  { file: 'logro-09.jpg', year: 2024, es: 'Cumpliendo la mitzvá de Sukot', en: 'Fulfilling the Sukkot mitzvah' },
  { file: 'logro-10.jpg', year: 2024, es: 'Encendiendo la janukiá', en: 'Lighting the Hanukkiah' },
  { file: 'logro-11.jpg', year: 2024, es: 'Entrega nocturna de Hanukkah a soldados', en: 'Night Hanukkah delivery to soldiers' },
  { file: 'logro-12.jpg', year: 2024, es: 'Soldados recibiendo su paquete de Hanukkah', en: 'Soldiers receiving their Hanukkah package' },
  { file: 'logro-13.jpg', year: 2024, es: 'Encendiendo velas de Hanukkah en el campo', en: 'Lighting Hanukkah candles in the field' },
  { file: 'logro-14.jpg', year: 2024, es: 'Entrega de kits a un grupo de soldados', en: 'Delivering kits to a group of soldiers' },
  { file: 'logro-16.jpg', year: 2025, es: 'Mishloach Manot para nuestros héroes', en: 'Mishloach Manot for our heroes' },
  { file: 'logro-17.jpg', year: 2025, es: 'Organizando donaciones para Pesach', en: 'Organizing Pesach donations' },
  { file: 'logro-18.jpg', year: 2025, es: 'Soldados en el desierto', en: 'Soldiers in the desert' },
  { file: 'logro-19.jpg', year: 2025, es: 'Con una familia junto a un vehículo militar', en: 'With a family by a military vehicle' },
  { file: 'logro-20.jpg', year: 2025, es: 'Soldados durante una entrega nocturna', en: 'Soldiers during a night delivery' },
  { file: 'logro-22.jpg', year: 2025, es: 'Entrega de arba minim en el campo', en: 'Delivering the four species in the field' },
  { file: 'logro-23.jpg', year: 2024, es: 'Soldados camino a celebrar Sukot', en: "Soldiers on their way to celebrate Sukkot" },
  { file: 'logro-24.jpg', year: 2026, es: 'Entrega de paquetes a soldados', en: 'Delivering packages to soldiers' },
]
